version: '3.10'

services:
  app:
    build: .

  db:
    container_name: postgres
    image: postgres:16-alpine
    restart: always

    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USERNAME: local
      POSTGRES_DB: database
    ports:
      - "5432"