version: '3.9'

services:
  app:
    build: .
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: gorm
      POSTGRES_USER: gorm
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  db_data:

