version: '3.9'

services:
  app:
    build: ./cmd
  db:
    container_name: postgres
    image: postgres:16-alpine
    restart: always

    environment:
      POSTGRES_PASSWORD: gorm
      POSTGRES_USERNAME: gorm
      POSTGRES_DB: dbname
    ports:
      - "5432"