version: '3.9'

services:
  app:
    build: .
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: gorm
      POSTGRES_USER: gorm
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
  migrations:
      build: .
      depends_on:
        - db
      environment:
        DB_DSN: "host=db user=gorm password=gorm dbname=database sslmode=disable"
      command: [ "./main", "-migrate" ]


volumes:
  db_data:

